<a href="https://colab.research.google.com/github/Aya-ayh/git-hw/blob/main/Data%20Analysis/Level%201/pandas_for_data_analysis_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 📊 **Introduction to Pandas**

Pandas is a powerful Python library used for working with data in an easy and flexible way. It helps you analyze, clean, and manipulate data quickly, making it one of the most important tools in Data Science.

Think of Pandas as Excel inside Python—but much more powerful and automated.

# **🚀 Why do we use Pandas?**

Pandas makes it easy to:

Load data from files (CSV, Excel, JSON, etc.)

Clean messy data (missing values, duplicates, errors)

Analyze and explore data

Transform and reshape data

Perform statistical calculations

Work with time-based data (dates and trends)

# **🧱 Main Data Structures**

Pandas is built on two main structures:

## **1. Series 📌**

A Series is like a single column of data.

## **2. DataFrame 📊**

A DataFrame is like a table (rows and columns), similar to Excel.

# **🔑 Key Features of Pandas**
Handles missing data easily

Allows fast filtering and searching

Supports grouping and aggregation

Can merge and join datasets like databases

Works smoothly with large datasets

In [2]:
import pandas as pd

In [ ]:
help(pd)

## Step 1: Load Sample Data
We will create a small sample sales dataset manually to keep things simple.

In [7]:

data = {
    'Date': ['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04', '2026-05-04'],
    'Product': ['Apples', 'Bananas', 'Apples', 'Bananas', 'Orange'],
    'Quantity': [10, 15, 20, 5, 25],
    'Price': [0.5, 0.3, 0.5, 0.3, 0.7]
}
#the keys are the colunms and the values are the rows
df = pd.DataFrame(data)
df
#it will become as a list so there is index

         Date  Product  Quantity  Price
0  2023-01-01   Apples        10    0.5
1  2023-01-02  Bananas        15    0.3
2  2023-01-03   Apples        20    0.5
3  2023-01-04  Bananas         5    0.3
4  2026-05-04   Orange        25    0.7

## Step 2: Understand the Data

In [ ]:
help(df.info)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      5 non-null      object
 1   Product   5 non-null      object
 2   Quantity  5 non-null      int64
 3   Price     5 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes

## Step 3: Descriptive Statistics
Get a quick summary of numeric columns.

In [ ]:
help(df.describe)

In [14]:
df.describe()

        Quantity     Price
count   5.000000  5.000000
mean   15.000000  0.460000
std     7.905694  0.167332
min     5.000000  0.300000
25%    10.000000  0.300000
50%    15.000000  0.500000
75%    20.000000  0.500000
max    25.000000  0.700000

## Step 4: Create a New Column
We can calculate `Revenue = Quantity × Price`.

In [20]:
df['Revenue'] = df['Quantity'] * df['Price']
df
#or
print(df)
print(df.head(2))#to tell how many rows you want
print(df.tail(2))
# try  df['new column']=1

         Date  Product  Quantity  Price  Revenue
0  2023-01-01   Apples        10    0.5      5.0
1  2023-01-02  Bananas        15    0.3      4.5
2  2023-01-03   Apples        20    0.5     10.0
3  2023-01-04  Bananas         5    0.3      1.5
4  2026-05-04   Orange        25    0.7     17.5
         Date  Product  Quantity  Price  Revenue
0  2023-01-01   Apples        10    0.5      5.0
1  2023-01-02  Bananas        15    0.3      4.5
         Date  Product  Quantity  Price  Revenue
3  2023-01-04  Bananas         5    0.3      1.5
4  2026-05-04   Orange        25    0.7     17.5

In [ ]:
help(df.head())
help(df.tail())

## Step 5: Filter Rows
Let's filter rows where Revenue is greater than 5.

In [21]:
df[df['Revenue'] > 5]

         Date Product  Quantity  Price  Revenue
2  2023-01-03  Apples        20    0.5     10.0
4  2026-05-04  Orange        25    0.7     17.5

In [22]:
df[df['Product'] == 'Apples']

         Date Product  Quantity  Price  Revenue
0  2023-01-01  Apples        10    0.5      5.0
2  2023-01-03  Apples        20    0.5     10.0

## Step 6: Group By Product
Total revenue per product.

In [23]:
df.groupby('Product')['Revenue'].sum()

Product
Apples     15.0
Bananas     6.0
Orange     17.5
Name: Revenue, dtype: float64

In [25]:
df.groupby('Product')['Quantity'].sum()

Product
Apples     30
Bananas    20
Orange     25
Name: Quantity, dtype: int64

## Step 7: Sorting the DataFrame
Sort by revenue in descending order.

In [ ]:
help(df.sort_values)

In [26]:
df.sort_values(by='Revenue', ascending=False)
#from greater to less(desascending)

         Date  Product  Quantity  Price  Revenue
4  2026-05-04   Orange        25    0.7     17.5
2  2023-01-03   Apples        20    0.5     10.0
0  2023-01-01   Apples        10    0.5      5.0
1  2023-01-02  Bananas        15    0.3      4.5
3  2023-01-04  Bananas         5    0.3      1.5

## Step 8: Handling Missing Values
Let's simulate missing data and handle it.

In [27]:

df.loc[2, 'Quantity'] = None
print("With missing value:")
print(df)

# Fill missing value with 0
df['Quantity'] = df['Quantity'].fillna(0)
#na= not avilable
#ex.   df['Quantity'].fillna(df['Quantity'].medin()) or mode and so on
print("After filling missing value:")
print(df)

With missing value:
         Date  Product  Quantity  Price  Revenue
0  2023-01-01   Apples      10.0    0.5      5.0
1  2023-01-02  Bananas      15.0    0.3      4.5
2  2023-01-03   Apples       NaN    0.5     10.0
3  2023-01-04  Bananas       5.0    0.3      1.5
4  2026-05-04   Orange      25.0    0.7     17.5
After filling missing value:
         Date  Product  Quantity  Price  Revenue
0  2023-01-01   Apples      10.0    0.5      5.0
1  2023-01-02  Bananas      15.0    0.3      4.5
2  2023-01-03   Apples       0.0    0.5     10.0
3  2023-01-04  Bananas       5.0    0.3      1.5
4  2026-05-04   Orange      25.0    0.7     17.5